Nas 35/layout list of workers
ErmolaevAlexey365/spinach_learning_frontend pull request #1
Opened 2023-03-03 02:14 UTC by NastyaIgnatchik

2023-03-03 11:01 UTC, ErmolaevAlexey365 requested changes

2023-03-03 11:01 UTC, ErmolaevAlexey365 commented on src/pages/profile/Profile.tsx
> +      .catch(function (error: any) {
any

2023-03-06 17:55 UTC, NastyaIgnatchik commented on src/pages/login/Login.tsx
>        .then((response: any) => {
Done

2023-03-06 18:14 UTC, NastyaIgnatchik commented on src/pages/profile/Profile.tsx
>    const [userData, setUserData] = useState<any>([{}]);
done

2023-03-06 18:18 UTC, NastyaIgnatchik commented on src/utils/dataSorting.ts
> +    // [
не нашла где

2023-03-06 19:07 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
> +  serviceUserAccount: any;
done

2023-03-06 19:08 UTC, NastyaIgnatchik commented on src/pages/dashboard/Dashboard.tsx
> +  async function submitForm(data: any) {
done

2023-03-06 19:09 UTC, NastyaIgnatchik commented on src/pages/dashboard/Dashboard.tsx
> +      .then((response: any) => {
done

2023-03-06 19:13 UTC, NastyaIgnatchik commented on src/pages/dashboard/Dashboard.tsx
> +      .then((response: any) => {
done

2023-03-06 19:13 UTC, NastyaIgnatchik commented on src/pages/profile/Profile.tsx
> +      .catch(function (error: any) {
done

2023-03-06 19:16 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
> +  submitForm: (data: any) => void;
done

2023-03-06 19:17 UTC, NastyaIgnatchik commented on src/components/service/userInstance.ts
> +  async startParser(body: any, token: string) {
done

2023-03-06 19:17 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +      .catch(function (error: any) {
done

2023-03-06 19:18 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +      .then((response: any) => {
done

2023-03-06 19:18 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +      .catch(function (error: any) {
done

2023-03-06 19:18 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +      .catch(function (error: any) {
done

2023-03-06 19:19 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +      .then((response: any) => {
done

2023-03-06 19:19 UTC, NastyaIgnatchik commented on src/components/lists/UserAccount.tsx
>        .catch(function (error: any) {
done

2023-03-06 19:20 UTC, NastyaIgnatchik commented on src/components/lists/UserAccount.tsx
>        .then((response: any) => {})
done

2023-03-06 19:20 UTC, NastyaIgnatchik commented on src/components/lists/Jobs.tsx
> +              return <Chip label={el} size="small" color="primary" />;
done

2023-03-06 19:22 UTC, NastyaIgnatchik commented on src/components/lists/Jobs.tsx
> +                  return <Chip label={el} size="small" color="primary" />;
done

2023-03-06 19:22 UTC, NastyaIgnatchik commented on src/components/lists/Jobs.tsx
> +                  return <Chip label={el} size="small" color="primary" />;
done

2023-03-06 19:23 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
>                        value={"2"}
done

2023-03-06 19:23 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +                      value={"1"}
done

2023-03-06 19:24 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
>                      {upworkAccounts.map((option: any) => (
done

2023-03-06 19:25 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
>    const [FixedPriceNumberMax, setFixedPriceNumberMax] = useState<any>("");
done

2023-03-06 19:26 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
>    const [hourlyNumberMin, setHourlyNumberMin] = useState<any>("");
done

2023-03-06 19:27 UTC, NastyaIgnatchik commented on src/components/buttons/verticalMenu/VertMenu.tsx
> +        {options.map((option: any) => (
done

2023-03-06 19:28 UTC, NastyaIgnatchik commented on src/components/buttons/verticalMenu/VertMenu.tsx
> +  const handleClose = (option: any) => {
done

2023-03-06 19:31 UTC, NastyaIgnatchik commented on src/components/buttons/verticalMenu/VertMenu.tsx
> +const VertMenu = ({ options, removeWorker }: any) => {
done

2023-03-06 19:32 UTC, NastyaIgnatchik commented on src/pages/dashboard/Dashboard.tsx
> +    async function submitForm (data: any) {
done

2023-03-06 19:33 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
> +     timer:any;
done

2023-03-06 19:34 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
> +    submitForm: (data:any)=>void;
done

2023-03-06 19:34 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
> +    submitForm: (data:any)=>void;
done

2023-03-06 19:35 UTC, NastyaIgnatchik commented on src/components/schemas/Schema.ts
> +    // timer: yup.number().required("This is a required field"),
done

2023-03-06 19:36 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +      <form onSubmit={handleSubmit((data:any)=>{
done

2023-03-07 21:13 UTC, NastyaIgnatchik commented on src/interfaces/interfaces.ts
done

2023-03-07 21:13 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +    // isCheckboxChecked()
done

2023-03-07 21:14 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> + // function isCheckboxChecked(){
done

2023-03-07 21:14 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +                {/*{errors.timer?.message}*/}
done

2023-03-07 21:14 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +                {/*{errors.timer?.message}*/}
done

2023-03-07 21:14 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
> +                    // checked={isCheckboxesChecked}
done

2023-03-07 21:14 UTC, NastyaIgnatchik commented on src/components/lists/Workers.tsx
> +import {IWorkersProps} from "../../interfaces/interfaces";
done

2023-03-07 21:15 UTC, NastyaIgnatchik commented on src/components/buttons/menuButton/MenuButton.tsx
> +import {Context} from "../../../context/context";
done

2023-03-07 21:15 UTC, NastyaIgnatchik commented on src/components/forms/worker/WorkerForm.tsx
>                  <Controller
done

2023-03-07 23:41 UTC, NastyaIgnatchik commented on src/components/modals/WorkerModal.tsx
>  const WorkerModal = ({  isModalOpen,setIsModalOpen }:IOpenModalButton) => {
done

2023-03-08 12:53 UTC, ErmolaevAlexey365 approved these changes

2023-03-08 12:54 UTC, merged